import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function buildFinanceReportPdf({
    title,
    periodLabel,
    queriedAt,
    summary,
    tableHeaders,
    tableRows,
    logoBase64
}) {
    const pdf = new jsPDF("p", "mm", "a4");

    const HEADER_HEIGHT = 45;

    if (logoBase64) {
        pdf.addImage(logoBase64, "PNG", 15, 12, 38, 0);
    }

    pdf.setFontSize(16);
    pdf.text(title, 15, HEADER_HEIGHT);

    pdf.setFontSize(11);
    pdf.text(`Period: ${periodLabel}`, 15, HEADER_HEIGHT + 8);

    if (queriedAt) {
        pdf.text(`Data queried at: ${queriedAt}`, 15, HEADER_HEIGHT + 14);
    }

    let y = HEADER_HEIGHT + 28;

    pdf.setFillColor(245);
    pdf.rect(12, y - 6, 186, summary.length * 8 + 10, "F");

    pdf.setFontSize(11);
    summary.forEach(row => {
        pdf.text(`${row.label}:`, 18, y);
        pdf.text(String(row.value ?? "—"), 80, y);
        y += 8;
    });

    if (tableHeaders.length && tableRows.length) {
        autoTable(pdf, {
            startY: y + 8,
            head: [tableHeaders],
            body: tableRows,
            styles: { fontSize: 10 },
            headStyles: { fillColor: [40, 40, 40] }
        });
    }

    const pageHeight = pdf.internal.pageSize.height;

    pdf.setFontSize(9);
    pdf.setTextColor(120);
    pdf.text(
        "© 2025 SIDAROO · Generated by Finance Manager",
        15,
        pageHeight - 15
    );

    pdf.save(`${title.replace(/\s+/g, "_")}.pdf`);
}
